"""Initial migration

Revision ID: 3bc6ae8d989c
Revises: 
Create Date: 2025-01-19 22:10:27.058753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc6ae8d989c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('housing_median_age', sa.Integer(), nullable=True),
    sa.Column('total_rooms', sa.Integer(), nullable=True),
    sa.Column('total_bedrooms', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('households', sa.Integer(), nullable=True),
    sa.Column('median_income', sa.Float(), nullable=True),
    sa.Column('median_house_value', sa.Float(), nullable=True),
    sa.Column('ocean_proximity', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('house_id'),
    sa.UniqueConstraint('house_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    # ### end Alembic commands ###
